#!/bin/sh

B="`dirname $0`"

cd "$B"

D1="`pwd`/tmp/dejumblefs_1"
D2="`pwd`/tmp/dejumblefs_2"

mkdir -p "$D1"
mkdir -p "$D2"

echo Ejecutando prueba A...
dejumble "$D1" -o root="$D2",filter="$2",cache="$3",organizer="$4"
./test_createdelete "$D1" "$D2" > pruebaA-$1.dat
umountdejumble "$D1"

echo Ejecutando prueba B...
dejumble "$D1" -o root="$D2",filter="$2",cache="$3",organizer="$4"
./test_createcontent "$D1" "$D2" > pruebaB-$1.dat
umountdejumble "$D1"

echo Los resultados fueron guardados en pruebaA-$1.dat y pruebaB-$1.dat

rm -rf "$D1"
rm -rf "$D2"

