#!/bin/sh

cd `dirname $0`

mkdir /tmp/dejumblefs_1
mkdir /tmp/dejumblefs_2

dejumble /tmp/dejumblefs_1 -o root="/tmp/dejumblefs_2",filter="$2",cache="$3",organizer="$4",noappledouble

echo Ejecutando prueba A...
./test_createdelete /tmp/dejumblefs_1 /tmp/dejumblefs_2 > pruebaA-$1.dat
echo Ejecutando prueba B...
./test_createcontent /tmp/dejumblefs_1 /tmp/dejumblefs_2 > pruebaB-$1.dat
echo Los resultados fueron guardados en pruebaA-$1.dat y pruebaB-$1.dat

umountdejumble /tmp/dejumblefs_1

rm -rf /tmp/dejumblefs_1
rm -rf /tmp/dejumblefs_2

