#!/usr/bin/env python

import sys
import logging
import logging.config
import pkg_resources
import gettext

import fuse
from fuse import Fuse

import dejumble.fs
from dejumble.fs import *

gettext.install('dejumble')

def main():
    global server

    usage = """
dejumble: presents the content of a directory in an organized structure.

""" + Fuse.fusage

    server = DejumbleFS(version="%prog " + fuse.__version__, 
                               usage=usage, 
                               dash_s_do='setsingle')

    server.parser.add_option(mountopt="root",
                             metavar="ROOT",
                             default='~/',
                             help=_("root for all file operations [default: %default]"))
    server.parser.add_option(mountopt="conf",
                             metavar="CONF",
                             default='~/.dejumblefs/default.xml',
                             help=_("read configuration from CONF file [default: %default]"))        
    server.parser.add_option(mountopt="filter",
                             metavar="FILTER",
                             default='OriginalDirectory',
                             help=_("use FILTER to handle QUERY [default: %default]"))
    server.parser.add_option(mountopt="cache",
                             metavar="CACHE",
                             default='WriteThrough',
                             help=_("use CACHE to handle caching [default: %default]"))
    server.parser.add_option(mountopt="organizer",
                             metavar="ORGANIZER",
                             default='Original',
                             help=_("use ORGANIZER [default: %default]"))
    server.parser.add_option(mountopt="query",
                             metavar="QUERY",
                             default='',
                             help=_("execute QUERY [default: %default]"))

    server.parse(values=server, errex=1)

    server.main()


if __name__ == '__main__':
    logging.config.fileConfig(pkg_resources.resource_filename('dejumble', 'conf/logging.conf'))

    # redirect stdout to a disk file
    saveout = sys.stdout
    saveerr = sys.stderr
    outfile = open('/tmp/log.txt', 'a+')
    sys.stdout = outfile
    sys.stderr = outfile

    # output stuff
    main()

    # restore stdout
    outfile.flush()
    outfile.close()
    sys.stdout = saveout
    sys.stderr = saveerr

